# Generated by Django 3.2.7 on 2021-10-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ratingapp', '0003_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.SlugField(),
        ),
    ]
