# Generated by Django 3.2.7 on 2021-10-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ratingapp', '0005_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Category',
        ),
    ]
