# Generated by Django 3.2.7 on 2021-10-02 09:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ratingapp', '0006_remove_review_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Ratings',
        ),
    ]
