# Generated by Django 3.2.7 on 2021-10-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ratingapp', '0007_rename_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='Posted_on',
            new_name='posted_on',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='Review',
            new_name='review',
        ),
    ]
